output: .

collections:
  - common
  - typescript

excludes:
  - .cspell.json
  - package.json
  - README.md

render_context:
  name: hashed-env
  description: Seed pseudo-random environment variables with a repository's git hash.
  version: 1.0.0
  author: joellefkowitz
  repository: https://github.com/JoelLefkowitz/hashed-env.git
  codacy_id: 14dda3ed73cc47cca315d9582ce93fb7
  keywords:
    - pseudo-random
    - environment
    - seed
    - git
    - hash
