severity: low
exclude:
  - message: Codacy project public id
    pattern: 14dda3ed73cc47cca315d9582ce93fb7

  - message: Sourcemaps
    pattern: sourceMappingURL=data:application/json;base64,

  - message: Giphy links
    pattern: https://media.giphy.com/media/

  - message: Dependencies
    paths:
      - package-lock.json
      - node_modules
      - venv
      - yarn-error.log
      - yarn.lock
